# Generated by Django 3.1.1 on 2021-08-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('space_number', models.IntegerField()),
                ('time_in', models.TextField()),
                ('time_out', models.TextField(blank=True)),
                ('price', models.IntegerField(default=-1)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('space_number', models.IntegerField()),
                ('time_in', models.TextField()),
                ('time_out', models.TextField(blank=True)),
                ('price', models.IntegerField(default=-1)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
